import { NextPage } from "next";
import Head from "next/head";
import { BackgroundEffect } from "../../ui/components/BackgroundEffect/BackgroundEffect";
import { Header } from "../../ui/components/Header/Header";
import React, { useEffect } from "react";
import { Heading, Section, TopLine } from "../../ui/styles/_pageElements";
import ReactHTMLParser from "react-html-parser";
import { Wrapper } from "../../ui/components/PageComponent/Wrapper/Wrapper";
import { useFormik } from "formik";
import { useForm } from "@formspree/react";
import styled from "styled-components";
import v from "../../ui/styles/_variables";
import { Button } from "../../ui/components/Button/Button";

const Form = styled.form`
  display: flex;
  flex-direction: column;
  max-width: 520px;
`;
const Input = styled.input`
  border: 2px solid black;
  width: 100%;
  padding: 10px 15px;
  font-size: 14px;
  border-radius: 3px;
  outline: none;
  transition: 0.2s ease-in-out;
  margin-bottom: 12px;
  &:focus {
    border: 2px solid ${v.primaryColor};
  }
`;
const TextArea = styled.textarea`
  border: 2px solid black;
  width: 100%;
  padding: 10px 15px;
  font-size: 14px;
  resize: none;
  border-radius: 3px;
  outline: none;
  margin-bottom: 15px;
  transition: 0.2s ease-in-out;
  &:focus {
    border: 2px solid ${v.primaryColor};
  }
`;

const Success = styled.p`
  color: green;
  font-size: 18px;
  font-family: ${v.secondaryFont};
`;

const Label = styled.label`
  margin-bottom: 5px;
  font-size: 14px;
`;

const Mail: NextPage = () => {
  const [state, handleSubmit] = useForm("moqyrgnk");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BackgroundEffect forPreview={false} />
        <Header />
        <Wrapper>
          <Section>
            <TopLine>
              <Heading>{"Свяжитесь с нами"}</Heading>
            </TopLine>
            <Form onSubmit={handleSubmit}>
              <Label htmlFor="">Ваш email</Label>
              <Input name={"Name"} type="email" required={true} />
              <Label htmlFor="">Текст сообщения</Label>
              <TextArea
                name="About"
                id="about"
                cols={30}
                rows={10}
                required={true}
              />
              {state.succeeded && <Success>Успешно отправлено!</Success>}
              <Button type={"submit"} disabled={state.succeeded}>
                Отправить
              </Button>
            </Form>
          </Section>
        </Wrapper>
      </main>
    </>
  );
};

export default Mail;
