import Head from "next/head";
import { BackgroundEffect } from "../../ui/components/BackgroundEffect/BackgroundEffect";
import { Header } from "../../ui/components/Header/Header";
import React from "react";
import { Wrapper } from "../../ui/components/PageComponent/Wrapper/Wrapper";
import { TopLine, Section, Heading } from "../../ui/styles/_pageElements";
import styled from "styled-components";
import ImageGallery from "react-image-gallery";
import "react-image-gallery/styles/css/image-gallery.css";
const Content = styled.div`
  & ul {
    & li {
      list-style: disc;
      list-style-position: inside;
      margin-bottom: 5px;
    }
  }
  & b {
    font-weight: 700;
  }
`;

const images = [
  {
    original: "https://picsum.photos/id/1018/1000/600/",
    thumbnail: "https://picsum.photos/id/1018/250/150/",
  },
  {
    original: "https://picsum.photos/id/1015/1000/600/",
    thumbnail: "https://picsum.photos/id/1015/250/150/",
  },
  {
    original: "https://picsum.photos/id/1019/1000/600/",
    thumbnail: "https://picsum.photos/id/1019/250/150/",
  },
];

const WrapperGallery = styled.div`
  max-width: 1200px;
  margin: 0 auto;
  margin-top: 40px;
  padding-bottom: 60px;
`;
const IndividualHistoryPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BackgroundEffect forPreview={false} />
        <Header />
        <Wrapper>
          <Section>
            <TopLine>
              <Heading>123123</Heading>
            </TopLine>
            <Content>
              <p>asdadasdadasdvgsasdaqewqwe</p>
              <p>
                <a href="https://yandex.ru">Фрэнсис Хетлинг</a> (англ. Francis
                Hetling) — <b>123</b> не существовавший пионер фотоискусства
                ранней Викторианской эпохи, под именем которого британский
                художник-руралист (англ.)русск. Грэм Овенден и фотограф Говард
                Грей (англ.)русск. экспонировали в Национальной портретной
                галерее в Лондоне на выставке в июле 1974 года и продавали
                созданные ими снимки-мистификации в стиле и технике фотографий
                XIX века. В 1980 году против Овендена и Грея был возбуждён
                судебный иск. Официальная формулировка иска звучала как «сговор
                [Грея и Овендена] между 1974 и 1978 годами с целью получения
                собственности обманным путём». В ходе судебного процесса
                выяснилось, что оба участника мистификации причастны к появлению
                фотографий Хетлинга. Грей отвечал за техническую сторону
                создания фотографий, а Овенден придал им внешний вид ранних
                викторианских калотипов. Овенден заявил в суде, что цель
                мистификации заключалась не в получении крупной суммы денег, а в
                том, чтобы «показать истинный уровень тех, кто занимается
                искусством, тех, кто объявляет себя экспертами, ничего не зная,
                [и] тех, кто получает прибыль, превращая эстетические ценности в
                финансовые». Грей и Овенден были оправданы решением коллегии
                присяжных. Судебный процесс широко освещался в средствах
                массовой информации Великобритании и анализируется в научных и
                научно-популярных работах, посвящённых фальсификации
                произведений искусства.
              </p>
              <ul>
                <li>123</li>
                <li>123</li>
                <li>123</li>
              </ul>
            </Content>
            <WrapperGallery>
              <ImageGallery autoPlay={true} lazyLoad={true} items={images} />
            </WrapperGallery>
          </Section>
        </Wrapper>
      </main>
    </>
  );
};

export default IndividualHistoryPage;
