import React from "react";
import Head from "next/head";
import { NextPage } from "next";
import { Header } from "../../ui/components/Header/Header";
import { BackgroundEffect } from "../../ui/components/BackgroundEffect/BackgroundEffect";
import "react-vertical-timeline-component/style.min.css";
import { CardHeading, TimeLine, Element } from "./history.style";
import v from "../../ui/styles/_variables";
import { SectionSeparator } from "../../ui/components/SectionSeparator/SectionSeparator";
import {
  TextBlock,
  TopLine,
  Section,
  Heading,
} from "../../ui/styles/_pageElements";
import { Stickers } from "../command/command.style";
import { Wrapper } from "../../ui/components/PageComponent/Wrapper/Wrapper";
import { Button } from "../../ui/components/Button/Button";
import styled from "styled-components";
import { getCommandPageInfo } from "../../lib/commanPage";
import { getCommandInfo } from "../../lib/commandData";
import Link from "next/link";
import {
  getHistoryContent,
  getHistoryPageData,
  historyContentData,
  historyPagePageInfo,
} from "../../lib/historyPage";
import ReactHTMLParser from "react-html-parser";

const timeLineIconStyle = { background: v.primaryColor, color: v.accentColor };

const ButtonCard = styled(Button)`
  margin-top: 20px;
  min-width: 120px;
  opacity: 1;
`;

const History: NextPage<{
  pageData: historyPagePageInfo;
  data: historyContentData[];
}> = ({ data, pageData }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BackgroundEffect forPreview={false} />
        <Header />
        <Wrapper>
          <Section>
            <TopLine>
              <div>
                <Heading>{pageData.heading}</Heading>
                <TextBlock
                  initial={{ opacity: 0, y: -50 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{
                    ease: ["easeInOut"],
                    duration: 0.7,
                    delay: 0.4,
                  }}
                >
                  {ReactHTMLParser(pageData.description)}
                </TextBlock>
              </div>
            </TopLine>
          </Section>
          <SectionSeparator />
          <TimeLine animate={false}>
            {data.map((item) => {
              return (
                <Element
                  key={item.id}
                  className="vertical-timeline-element--work"
                  date="13 – 15 Ноября 2020г"
                  iconStyle={timeLineIconStyle}
                >
                  <CardHeading className="vertical-timeline-element-title">
                    {ReactHTMLParser(item.heading)}
                  </CardHeading>
                  {ReactHTMLParser(item.description)}
                  <Link href={`/history/${item.id}`}>
                    <a>
                      <ButtonCard>Подробнее</ButtonCard>
                    </a>
                  </Link>
                </Element>
              );
            })}
          </TimeLine>
          <SectionSeparator inverted={true} />
        </Wrapper>
      </main>
    </>
  );
};

export async function getStaticProps() {
  // Получение и прокидывание данных перед самой сборкой статики
  const pageData = getHistoryPageData();
  const data = getHistoryContent();
  return {
    props: {
      pageData,
      data,
    },
  };
}

export default History;
