import type { NextPage } from "next";
import Head from "next/head";
import { Wrapper } from "../ui/components/Wrapper/Wrapper";
import { Header } from "../ui/components/Header/Header";
import Image from "next/image";
import { AccentButton } from "../ui/components/AccentButton/AccentButton";
import {
  Accent,
  AccentText,
  Content,
  ContentText,
  Heading,
  Main,
  TeamImage,
} from "./index.style";
import { motion } from "framer-motion";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Wrapper>
          <Header />
          <Content>
            <ContentText>
              <Heading
                initial={{ opacity: 0, x: -50 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 1 }}
              >
                Делаем продукты <br />
                Автоматизируем бизес <br />
                Едим детей <br />И просто красавчики
              </Heading>
              <Accent
                initial={{ opacity: 0, x: -50 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 1, delay: 0.7 }}
              >
                <AccentButton title={"Узнать подробнее"} />
                <AccentText>
                  «Самая дикая IT команда России. <br /> Качество - наше второе
                  имя. <br /> Пиво - третье!»
                </AccentText>
              </Accent>
            </ContentText>
            <TeamImage
              initial={{ opacity: 0, y: -50, scale: 0 }}
              animate={{ opacity: 1, y: 0, scale: 1, rotate: 1080 * 5 }}
              transition={{ duration: 1, delay: 0.4 }}
            >
              <Image
                layout={"responsive"}
                objectFit={"cover"}
                src={"/images/it-animals.svg"}
                width={"100%"}
                height={"100%"}
              />
            </TeamImage>
          </Content>
        </Wrapper>
      </Main>
    </div>
  );
};

export default Home;
