import type { NextPage } from "next";
import Head from "next/head";
import { Wrapper } from "../ui/components/PageComponent/Wrapper/Wrapper";
import { Header } from "../ui/components/Header/Header";
import Image from "next/image";
import { AccentButton } from "../ui/components/AccentButton/AccentButton";
import {
  Accent,
  AccentText,
  Content,
  ContentText,
  Heading,
  Main,
  TeamImage,
} from "./index.style";
import { BackgroundEffect } from "../ui/components/BackgroundEffect/BackgroundEffect";
import { CenterContent } from "../ui/components/CenterContent/CenterContent";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Header forPreviewPage={true} />
        <BackgroundEffect forPreview={true} />
        <CenterContent>
          <Wrapper>
            <Content>
              <ContentText>
                <Heading
                  initial={{ opacity: 0, x: -50 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ duration: 1 }}
                >
                  Делаем продукты <br />
                  Автоматизируем бизес <br />
                  Едим детей <br />И просто красавчики
                </Heading>
                <Accent
                  initial={{ opacity: 0, x: -50 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ duration: 1, delay: 0.7 }}
                >
                  <AccentButton title={"Узнать подробнее"} />
                  <AccentText>
                    «Самая дикая IT команда России. <br /> Качество - наше
                    второе имя. <br /> Пиво - третье!»
                  </AccentText>
                </Accent>
              </ContentText>
              <TeamImage
                initial={{ opacity: 0, y: -100 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 1, delay: 0.4 }}
              >
                <Image
                  layout={"responsive"}
                  objectFit={"cover"}
                  src={"/images/it-animals.svg"}
                  width={"100%"}
                  height={"100%"}
                />
              </TeamImage>
            </Content>
          </Wrapper>
        </CenterContent>
      </Main>
    </>
  );
};

export default Home;
