import Head from "next/head";
import { Header } from "../../ui/components/Header/Header";
import React from "react";
import { Wrapper } from "../../ui/components/PageComponent/Wrapper/Wrapper";
import { BusinessCard } from "../../ui/components/BussinesCard/BusinessCard";
import { BackgroundEffect } from "../../ui/components/BackgroundEffect/BackgroundEffect";

const DimaPage: ComponentType<unknown> = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <BackgroundEffect config={"dima"} forPreview={false} />
        <Header />
        <Wrapper>
          <BusinessCard type={"dima"} />
        </Wrapper>
      </main>
    </>
  );
};

export default DimaPage;
