import React from "react";
import Head from "next/head";
import { NextPage } from "next";
import { Header } from "../../ui/components/Header/Header";
import { Wrapper } from "../../ui/components/PageComponent/Wrapper/Wrapper";
import { PageSection } from "../../ui/components/PageComponent/PageSection/PageSection";
import { MainHeading } from "../../ui/components/MainHeading/MainHeading";
import styled, { css } from "styled-components";
import { StickerGallery } from "../../ui/components/StickerGallery/StickerGallery";
import { CommandList } from "../../ui/components/CommandList/CommandList";
import { SectionSeparator } from "../../ui/components/SectionSeparator/SectionSeparator";
import { BackgroundEffect } from "../../ui/components/BackgroundEffect/BackgroundEffect";
import { mxm } from "../../ui/styles/_mixin";
import { motion } from "framer-motion";

const TextBlock = styled(motion.div)`
  max-width: 550px;
`;

const TopLine = styled.div`
  display: flex;
  justify-content: space-between;
  align-items: center;
`;

const Stickers = styled(StickerGallery)`
  margin: 60px 40px 0 0;
  ${mxm(
    800,
    css`
      display: none;
    `
  )}
`;

const Section = styled.main`
  margin-top: 35px;
`;

const Heading = motion.h2;

const Command: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BackgroundEffect forPreview={false} />
        <Header />
        <Section>
          <Wrapper>
            <TopLine>
              <div>
                <Heading
                  initial={{ opacity: 0, y: -50 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ ease: ["easeInOut"], duration: 0.7, delay: 0 }}
                >
                  О команде
                </Heading>
                <TextBlock
                  initial={{ opacity: 0, y: -50 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{
                    ease: ["easeInOut"],
                    duration: 0.7,
                    delay: 0.4,
                  }}
                >
                  <p>IT-animals – это самая крутая команда работки в России</p>
                  <p>
                    Команда ― это группа лиц, объединённая общими мотивами,
                    интересами, идеалами, действующая сообща. Участники команды
                    объединены поддержкой друг друга и несут коллективную
                    ответственность за результат деятельности всей команды.
                  </p>
                  <p>
                    Команды подходят для решения задач высокой сложности, ведь
                    каждый участник команды специализируется на выполнении
                    какого-либо своего одного дела.
                  </p>
                </TextBlock>
              </div>
              <Stickers />
            </TopLine>
            <SectionSeparator />
          </Wrapper>
        </Section>
        <CommandList />
        <SectionSeparator inverted={true} />
      </main>
    </>
  );
};

export default Command;
