import React from "react";
import Head from "next/head";
import { NextPage } from "next";
import { Header } from "../../ui/components/Header/Header";
import { Wrapper } from "../../ui/components/PageComponent/Wrapper/Wrapper";
import { CommandList } from "../../ui/components/CommandList/CommandList";
import { SectionSeparator } from "../../ui/components/SectionSeparator/SectionSeparator";
import { BackgroundEffect } from "../../ui/components/BackgroundEffect/BackgroundEffect";
import {
  Heading,
  Section,
  Stickers,
  TextBlock,
  TopLine,
} from "./command.style";

const Command: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <BackgroundEffect forPreview={false} />
        <Header />
        <Section>
          <Wrapper>
            <TopLine>
              <div>
                <Heading
                  initial={{ opacity: 0, y: -50 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ ease: ["easeInOut"], duration: 0.7, delay: 0 }}
                >
                  О команде
                </Heading>
                <TextBlock
                  initial={{ opacity: 0, y: -50 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{
                    ease: ["easeInOut"],
                    duration: 0.7,
                    delay: 0.4,
                  }}
                >
                  <p>IT-animals – это самая крутая команда работки в России</p>
                  <p>
                    Команда ― это группа лиц, объединённая общими мотивами,
                    интересами, идеалами, действующая сообща. Участники команды
                    объединены поддержкой друг друга и несут коллективную
                    ответственность за результат деятельности всей команды.
                  </p>
                  <p>
                    Команды подходят для решения задач высокой сложности, ведь
                    каждый участник команды специализируется на выполнении
                    какого-либо своего одного дела.
                  </p>
                </TextBlock>
              </div>
              <Stickers />
            </TopLine>
            <SectionSeparator />
          </Wrapper>
        </Section>
        <CommandList />
        <SectionSeparator inverted={true} />
      </main>
    </>
  );
};

export default Command;
